name: repro_lsp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: ^2.2.0
  bloc: any
  flutter_bloc: any
  cupertino_icons: ^1.0.2

dependency_overrides:
  analyzer: 5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  freezed: ^2.2.0

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
